version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
     - 5442:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: test
